---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-0711
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-0711 
  name: audio-0711
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi